FROM n8n/n8n:1.36.2

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=tonyadmin
ENV N8N_BASIC_AUTH_PASSWORD=SecurePass123
ENV N8N_AUTH_EXCLUDE_ENDPOINTS=""
ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=5678

ENV N8N_USER_MANAGEMENT_DISABLED=false
ENV N8N_USER_MANAGEMENT_EMAIL=tony@pitwood.com
ENV N8N_USER_MANAGEMENT_FIRST_NAME=Tony
ENV N8N_USER_MANAGEMENT_LAST_NAME=Pitwood
ENV N8N_USER_MANAGEMENT_PASSWORD=SecurePass123

CMD ["n8n"]