services:
  - type: web
    name: n8n-legal-contract
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: n8n
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: tonyAdmin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: SecurePassword123
